- hosts: localhost
  gather_facts: true
  vars:
    alumno:
      nombre: "Agustín"
      apellido: "Zegarra"
      division: "202406"
    equipo:
      ip: "{{ ansible_default_ipv4.address }}"
      distro: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
      cores: "{{ ansible_processor_count }}"
  roles:
    - parcial
